name: Deploy to GitHub Pages

on:
  push:
    branches: [ "gh-pages" ]  # یا "main" اگر branch شما main است

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build project
      run: dotnet build --no-restore --configuration Release
    
    - name: Publish project
      run: dotnet publish -c Release -o ./publish
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./publish/wwwroot
        publish_branch: gh-pages
        keep_files: false